-- Magnetic Source Ltd: minimal free-tier-conscious commerce schema.
-- This script creates catalogue, demo-order, profile, and empty image-storage support.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id) values (new.id) on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  summary text,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  category text not null,
  price numeric(10,2) not null check (price >= 0),
  sku text not null unique,
  availability text not null default 'In stock',
  pack text not null,
  description text not null,
  image text,
  tags text[] not null default array['Trade edit'],
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.demo_orders (
  id uuid primary key default gen_random_uuid(),
  order_reference text not null unique,
  customer_name text not null,
  customer_email text not null,
  company text,
  address_line_1 text not null,
  address_line_2 text,
  city text not null,
  postcode text not null,
  subtotal numeric(10,2) not null check (subtotal >= 0),
  status text not null default 'Demo order',
  created_at timestamptz not null default now()
);

create table if not exists public.demo_order_items (
  id bigint generated by default as identity primary key,
  demo_order_id uuid not null references public.demo_orders(id) on delete cascade,
  product_sku text not null,
  product_name text not null,
  unit_price numeric(10,2) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0)
);

create or replace function public.create_demo_order_with_items(
  p_order_reference text,
  p_customer_name text,
  p_customer_email text,
  p_company text,
  p_address_line_1 text,
  p_address_line_2 text,
  p_city text,
  p_postcode text,
  p_subtotal numeric,
  p_items jsonb
)
returns uuid language plpgsql security definer set search_path = public as $$
declare
  v_order_id uuid;
begin
  insert into public.demo_orders (order_reference, customer_name, customer_email, company, address_line_1, address_line_2, city, postcode, subtotal, status)
  values (p_order_reference, p_customer_name, p_customer_email, nullif(p_company, ''), p_address_line_1, nullif(p_address_line_2, ''), p_city, p_postcode, p_subtotal, 'Demo order')
  returning id into v_order_id;

  insert into public.demo_order_items (demo_order_id, product_sku, product_name, unit_price, quantity)
  select v_order_id, item.product_sku, item.product_name, item.unit_price, item.quantity
  from jsonb_to_recordset(p_items) as item(product_sku text, product_name text, unit_price numeric, quantity integer);

  return v_order_id;
end;
$$;

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.demo_orders enable row level security;
alter table public.demo_order_items enable row level security;

drop policy if exists "Public can read categories" on public.categories;
drop policy if exists "Public can read products" on public.products;
drop policy if exists "Admin manages categories" on public.categories;
drop policy if exists "Admin manages products" on public.products;
drop policy if exists "Admin reads profiles" on public.profiles;
drop policy if exists "Visitors can create demo orders" on public.demo_orders;
drop policy if exists "Admin manages demo orders" on public.demo_orders;
drop policy if exists "Visitors can add demo order items" on public.demo_order_items;
drop policy if exists "Admin manages demo order items" on public.demo_order_items;

create policy "Public can read categories" on public.categories for select using (true);
create policy "Public can read products" on public.products for select using (true);
create policy "Admin manages categories" on public.categories for all using (public.is_admin()) with check (public.is_admin());
create policy "Admin manages products" on public.products for all using (public.is_admin()) with check (public.is_admin());
create policy "Admin reads profiles" on public.profiles for select using (public.is_admin() or id = auth.uid());
create policy "Visitors can create demo orders" on public.demo_orders for insert with check (true);
create policy "Admin manages demo orders" on public.demo_orders for all using (public.is_admin()) with check (public.is_admin());
create policy "Visitors can add demo order items" on public.demo_order_items for insert with check (true);
create policy "Admin manages demo order items" on public.demo_order_items for all using (public.is_admin()) with check (public.is_admin());

grant execute on function public.create_demo_order_with_items(text, text, text, text, text, text, text, text, numeric, jsonb) to anon, authenticated;

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

drop policy if exists "Public can read product images" on storage.objects;
drop policy if exists "Admin uploads product images" on storage.objects;
drop policy if exists "Admin updates product images" on storage.objects;
drop policy if exists "Admin removes product images" on storage.objects;

create policy "Public can read product images" on storage.objects for select using (bucket_id = 'product-images');
create policy "Admin uploads product images" on storage.objects for insert with check (bucket_id = 'product-images' and public.is_admin());
create policy "Admin updates product images" on storage.objects for update using (bucket_id = 'product-images' and public.is_admin());
create policy "Admin removes product images" on storage.objects for delete using (bucket_id = 'product-images' and public.is_admin());
