/**
 * Trade Ledger, Recut: original practical support copy for brand approval,
 * preserving a calm left rail, clear information hierarchy, and robust path
 * normalization so each information route retains its own approved copy.
 */
import { ArrowRight, Check, ChevronRight } from "lucide-react";
import { Link, useLocation } from "wouter";
import StoreLayout from "@/components/StoreLayout";

type InfoPageContent = { eyebrow: string; title: string; intro: string; evidence?: string[]; sections: { title: string; paragraphs: string[]; points?: string[] }[] };

const content: Record<string, InfoPageContent> = {
 "/about": { eyebrow:"About Magnetic Source", title:"About Magnetic Source UK wholesale supply", intro:"Magnetic Source Ltd is a curated UK trade source for smaller retailers and marketplace sellers looking for practical, dependable lines.", sections:[{title:"A smaller clearer",paragraphs:["The range is structured as a practical selection of useful, compact lines that can be understood quickly by buyers and displayed confidently by retailers."]},{title:"Made for the working retailer",paragraphs:["Product cards keep pack format, SKU, product information and customer price access close to the decision. The structure supports straightforward buying conversations instead of unnecessary platform complexity."],points:["Clear product information", "Customer login for pricing", "No fictitious reviews or demand claims"]},{title:"Registered company details",paragraphs:["Magnetic Source Ltd is registered in England and Wales. Registered address: Flat 1, Saviours House, 15 Newport Road, Hayes, England, UB4 8FR.","Company number: 15466397. VAT number: GB469 1754 52. Telephone: +44 7856 262726."]},{title:"How the catalogue works",paragraphs:["The storefront and basket let buyers review catalogue lines, while customer login keeps price access controlled before any future fulfilment or payment process is introduced."]}] },
 "/delivery-returns": { eyebrow:"Delivery & returns", title:"Delivery and returns for trade buyers", intro:"We keep delivery conversations straightforward. Once we have reviewed your selected lines and destination, the trade desk will confirm availability, delivery options and the next commercial step in writing.", evidence:["£200 ex VAT delivery threshold", "UK trade-desk confirmation", "Written return instructions"], sections:[{title:"Delivery planning",paragraphs:["Add the lines you need to your basket or contact the trade desk with your delivery postcode. We will confirm the practical delivery route, expected timing and any applicable charge before an order is accepted.","Free delivery is available on qualifying UK mainland orders over £200 excluding VAT, subject to confirmation of the final order and delivery address."]},{title:"Returns and issues",paragraphs:["If there is a problem with an agreed delivery, contact the trade desk before returning any goods. Please keep the products and their original packaging available while we review the issue and provide the appropriate return instructions."]},{title:"Clear confirmation",paragraphs:["Every accepted order is confirmed in writing with the agreed products, quantities, delivery arrangements and commercial terms. This avoids assumptions and gives both sides a clear record before fulfilment."]}] },
 "/privacy": { eyebrow:"Privacy", title:"Magnetic Source privacy notice", intro:"This notice explains how Magnetic Source Ltd handles personal information provided through the catalogue, customer account and contact routes.", evidence:["Customer account details", "Essential basket storage", "Direct privacy contact"], sections:[{title:"Information we collect",paragraphs:["When you contact us, create a customer account or submit an order request, we may receive the details you provide, including your name, business name, email address, telephone number, delivery information and the catalogue lines you are interested in. We use this information to operate customer access and respond to your request."]},{title:"How information is used",paragraphs:["We use customer account and order-request information to maintain correspondence, support customer price access and respond to product questions. Essential browser storage is used to keep your selected basket lines on your device while you browse the catalogue."]},{title:"Service partners and security",paragraphs:["The website relies on selected technical providers for hosting, database and security functions. Access to personal information is limited to what is needed to operate the service and respond to customer support requests."]},{title:"Your privacy request",paragraphs:["You may ask about the personal information connected with your customer account or order request by contacting the trade desk. Write to Magnetic Source Ltd, Flat 1, Saviours House, 15 Newport Road, Hayes, England, UB4 8FR, email info@magneticsource.uk or call +44 7856 262726."]}] },
 "/terms": { eyebrow:"Terms", title:"Magnetic Source website terms", intro:"These terms set out the basis on which trade buyers may use the Magnetic Source catalogue and customer account services.", evidence:["Pack and reference information", "Written acceptance", "UK registered company"], sections:[{title:"Catalogue information",paragraphs:["We present product names, pack formats, references and other catalogue details to support informed product selection. The range changes over time, so availability, pricing and delivery information may be reviewed before an order is accepted."]},{title:"Customer accounts and order requests",paragraphs:["A customer login provides controlled access to catalogue pricing when a current price list is available. Submitting an order request does not reserve stock, create a contract or take payment. Any contract is formed only when Magnetic Source confirms the agreed products and commercial terms in writing."]},{title:"Use of the website",paragraphs:["You must use this website lawfully and responsibly. You must not attempt unauthorised access, interfere with the site or misuse catalogue material. We may update the catalogue and these terms when operationally necessary."]},{title:"Company details",paragraphs:["Magnetic Source Ltd is registered in England and Wales. Registered address: Flat 1, Saviours House, 15 Newport Road, Hayes, England, UB4 8FR. Company number: 15466397. VAT number: GB469 1754 52. Telephone: +44 7856 262726."]}] },
 "/trade-account": { eyebrow:"Trade account", title:"Create your customer login", intro:"Magnetic Source works with UK retailers and marketplace sellers looking for practical product lines, clear pack information and controlled customer price access.", evidence:["Pack formats and product references", "Customer price access", "Commercial details in writing"], sections:[{title:"Tell us about your business",paragraphs:["Introduce your business, the retail channel you serve and the departments you are interested in. A short overview helps the trade desk prepare a more useful response."]},{title:"Create your login",paragraphs:["Browse the catalogue and use the Login to see price button to create a customer account. Once the latest price list is published, your signed-in account will provide the appropriate price access."],points:["Clear product references and pack formats", "A direct route to the trade desk", "Commercial details confirmed before acceptance"]},{title:"What happens next",paragraphs:["We will review the information you provide and respond with the next practical step. Creating a customer login does not reserve stock, create credit or form an order; it gives you controlled access to the catalogue experience."]}] },
};

export default function InfoPage() {
 const [location] = useLocation();
 const pagePath = (location.split(/[?#]/)[0] || "/").replace(/\/+$/, "") || "/";
 const page = content[pagePath] || content["/about"];
 return <StoreLayout><section className="info-hero"><div className="trade-shell"><p className="eyebrow">{page.eyebrow}</p><h1>{page.title}</h1><p>{page.intro}</p>{page.evidence && <div className="info-evidence" aria-label="Trade information">{page.evidence.map((item) => <span key={item}>{item}</span>)}</div>}</div></section><div className="trade-shell info-layout section-space"><aside className="info-rail"><p className="eyebrow">On this page</p>{page.sections.map((section, index) => <a key={section.title} href={`#info-${index}`}><span>{String(index + 1).padStart(2,"0")}</span>{section.title}<ChevronRight size={15} /></a>)}<Link href="/contact" className="info-rail-contact">Talk to the trade desk <ArrowRight size={15} /></Link></aside><article className="info-content">{page.sections.map((section,index) => <section id={`info-${index}`} key={section.title}><span className="section-number">{String(index + 1).padStart(2,"0")}</span><h2>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.points && <ul>{section.points.map((point) => <li key={point}><Check size={17} /> {point}</li>)}</ul>}</section>)}</article></div></StoreLayout>;
}
