/**
 * Trade Ledger, Recut: original practical support copy for brand approval,
 * preserving a calm left rail and clear information hierarchy.
 */
import { ArrowRight, Check, ChevronRight } from "lucide-react";
import { Link, useLocation } from "wouter";
import StoreLayout from "@/components/StoreLayout";

type InfoPageContent = { eyebrow: string; title: string; intro: string; sections: { title: string; paragraphs: string[]; points?: string[] }[] };

const content: Record<string, InfoPageContent> = {
  "/about": { eyebrow:"About Magnetic Source", title:"Practical stock, deliberately selected.", intro:"Magnetic Source Ltd is a curated UK trade source for smaller retailers and marketplace sellers looking for practical, dependable lines.", sections:[{title:"A smaller, clearer edit",paragraphs:["The range is structured as a practical selection of useful, compact lines that can be understood quickly by buyers and displayed confidently by retailers."]},{title:"Made for the working retailer",paragraphs:["Product cards keep pack format, SKU, price and availability close to the decision. The structure supports straightforward buying conversations instead of unnecessary platform complexity."],points:["Clear product information", "GBP (£) price language", "No fictitious reviews or demand claims"]},{title:"How the catalogue works",paragraphs:["The storefront, basket and no-payment enquiry journey let buyers review catalogue lines before any future fulfilment or payment process is introduced."]}] },
  "/delivery-returns": { eyebrow:"Delivery & returns", title:"Clear terms before the parcel moves.", intro:"Magnetic Source currently uses a no-payment trade enquiry flow. Delivery costs, dispatch dates and any applicable return arrangements must be agreed with the trade desk before an order is accepted.", sections:[{title:"Delivery enquiries",paragraphs:["Use the contact form to ask about delivery availability, destination coverage and estimated dispatch timing for the lines you need. No carrier booking or payment is completed through this website."]},{title:"Returns",paragraphs:["If a future order is accepted, return eligibility, timeframe and return instructions will be confirmed in the applicable order documentation. Do not send goods back without written return instructions from the trade desk."]},{title:"Before launch of live sales",paragraphs:["This page must be updated with the business's approved delivery charge, dispatch, cancellation and returns terms before the website accepts payment or live fulfilment requests."],points:["No payment collection", "No live carrier integration", "Written trade confirmation before fulfilment"]}] },
  "/privacy": { eyebrow:"Privacy", title:"Information should have a purpose.", intro:"This working privacy notice explains the limited information used by the current catalogue and enquiry experience. It should be reviewed and completed with the business's final contact, retention and processor details before live sales begin.", sections:[{title:"Information we use",paragraphs:["The basket uses essential browser storage to retain selected products on your device. If you submit a trade enquiry or no-payment order request, the form may collect the name, email address, company, address and product details you provide so the enquiry can be reviewed."]},{title:"Service providers",paragraphs:["The website uses Supabase for database and authentication services and Vercel for website hosting. These providers process technical information needed to operate the service. Analytics should only be enabled after the business has selected a provider and updated this notice." ]},{title:"Your choices",paragraphs:["You can clear local basket data in your browser at any time. To ask about information held in a trade enquiry, contact the trade desk using the details on this site. The business must add its final legal identity, address, retention periods and rights process before accepting live customer orders." ]}] },
  "/terms": { eyebrow:"Terms", title:"The commercial detail belongs in the open.", intro:"These working website terms govern use of the Magnetic Source catalogue and enquiry experience. They should be reviewed and completed with the business's final legal identity and trading terms before live sales begin.", sections:[{title:"Catalogue information",paragraphs:["Product descriptions, pricing, availability and pack formats are provided to help trade buyers make an enquiry. They may be updated as the range changes and should be confirmed with the trade desk before an order is accepted." ]},{title:"Trade enquiries",paragraphs:["Submitting an enquiry or using the no-payment checkout does not create a contract, reserve stock or authorise payment. A contract can only arise after the business has confirmed the applicable products, price, delivery and any other commercial terms in writing." ]},{title:"Website use",paragraphs:["You must use the website lawfully and must not interfere with its operation, attempt unauthorised access, or misuse catalogue content. The business should add its registered address, company number, governing law and final contact details before live trading." ]}] },
};

export default function InfoPage() {
  const [location] = useLocation();
  const page = content[location] || content["/about"];
  return <StoreLayout><section className="info-hero"><div className="trade-shell"><p className="eyebrow">{page.eyebrow}</p><h1>{page.title}</h1><p>{page.intro}</p></div></section><div className="trade-shell info-layout section-space"><aside className="info-rail"><p className="eyebrow">On this page</p>{page.sections.map((section, index) => <a key={section.title} href={`#info-${index}`}><span>{String(index + 1).padStart(2,"0")}</span>{section.title}<ChevronRight size={15} /></a>)}<Link href="/contact" className="info-rail-contact">Talk to the trade desk <ArrowRight size={15} /></Link></aside><article className="info-content">{page.sections.map((section,index) => <section id={`info-${index}`} key={section.title}><span className="section-number">{String(index + 1).padStart(2,"0")}</span><h2>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.points && <ul>{section.points.map((point) => <li key={point}><Check size={17} /> {point}</li>)}</ul>}</section>)}</article></div></StoreLayout>;
}
